#!/usr/local/bin/python3
import urllib.request
import sys
import json
import re
import os
from termcolor import colored, cprint

INPUT_TEXT       = "SAMPLE INPUT"
OUTPUT_TEXT      = "SAMPLE OUTPUT"
EXPLANATION      = "EXPLANATION"
BASE_URL         = "https://www.hackerrank.com/rest/contests/master/challenges/"
FILE_SUFFIX_CODE = ".py"
FILE_SUFFIX_TEST = "_test"
FILE_EXT_IN      = ".in"
FILE_EXT_OUT     = ".out"

def main(argv = None):
    if argv is None:
        argv = sys.argv

    if len(sys.argv) > 1:
        pbName = sys.argv[1]
    else:
        print ("Need one argument")
        sys.exit()

    httpObj    = urllib.request.urlopen(BASE_URL + pbName)
    jsonStream = httpObj.read()
    jsonData   = json.loads(jsonStream.decode())
    # Clean up
    httpObj.close()

    pythonCodeTemplate = """\
#!/usr/local/bin/python3

import sys

def main(argv = None):
    if argv is None:
        argv = sys.argv



# Invoking the program entry point
if __name__ == "__main__":
    sys.exit(main())
"""

    fname = getFileName(pbName)

    fcode = open(fname + FILE_SUFFIX_CODE, 'w')
    fcode.write(pythonCodeTemplate)
    os.chmod(fname + FILE_SUFFIX_CODE, 0o744)       # Permissions have to be in octal
    cprint("In file " + fname + FILE_SUFFIX_CODE, "green")
    print("\n" + pythonCodeTemplate + "\n\n")
    fcode.close()

    # Have to check, the JSON is not always the same
    if "model" in jsonData:
        if "_data" in jsonData["model"]:
            if "python3_template" in jsonData["model"]["_data"]:
                pythonCodeTemplate += jsonData["model"]["_data"]["python3_template"]

    body  = jsonData["model"]["body_html"]

    useCaseNumber = 0
    while body.upper().find(INPUT_TEXT) != -1:
        body = parseUseCase(body, fname, useCaseNumber)
        useCaseNumber += 1

def parseUseCase(content, fname, number):
    start = content.upper().index(INPUT_TEXT)
    end   = content.upper().index(EXPLANATION)
    body  = content[start:end]

    startInput  = body.index("<code>")
    endInput    = body.index("</code>")
    sampleInput = body[(startInput+6):endInput]
    finname     = fname + FILE_SUFFIX_TEST + str(number) + FILE_EXT_IN
    fin         = open(finname, 'w')
    fin.write(sampleInput)
    cprint("In file " + finname, "green")
    print("\n" + sampleInput + "\n\n")
    fin.close

    start        = body.upper().index(OUTPUT_TEXT)
    body         = body[start:]
    startOutput  = body.index("<code>")
    endOutput    = body.index("</code>")
    sampleOutput = body[(startOutput+6):endOutput]
    foutname     = fname + FILE_SUFFIX_TEST + str(number) + FILE_EXT_OUT
    fout         = open(foutname, 'w')
    fout.write(sampleOutput)
    cprint("In file " + foutname, "green")
    print("\n" + sampleOutput + "\n\n")
    fout.close

    return content[end + len(EXPLANATION):]

def getFileName(pbName):
    pbName = pbName.replace('-', '_')
    return to_camelcase(pbName)

def to_camelcase(s):
    return re.sub(r'(?!^)_([a-zA-Z])', lambda m: m.group(1).upper(), s)

# Invoking the program entry point
if __name__ == "__main__":
    sys.exit(main())
