#!/usr/local/bin/python3
import sys
import os
from subprocess import call
from termcolor import colored, cprint

if (len(sys.argv) > 1):
    problemName = sys.argv[1]
else:
    print("You must pass a problem name as parameter")
    sys.exit()

script             = problemName + '.py'
inputTest          = problemName + '_test.in'
expectedOutputTest = problemName + '_test.out'
actualOutputTest   = problemName + '_run.out'

# Executes the script
fin  = open(inputTest, 'r')
fout = open(actualOutputTest, 'w')
call("python3 " + script, stdin=fin, stdout=fout, shell=True)

# Compares the output to the expected result
fileDiff = "temp_diff"
fdiff = open(fileDiff, 'w')
call("diff " + actualOutputTest + " " + expectedOutputTest, stdout=fdiff, shell=True)

# Gets the pass / fail
s = os.stat(fileDiff)
if s.st_size == 0:
    cprint( "Success", "green" )
else:
    cprint( "Failure", "red" )

# Cleans up
fin.close()
fout.close()
fdiff.close()

os.remove(actualOutputTest)
os.remove(fileDiff)

# vim: ft=python
